#include "engine/rendering/opengl/opengl.hpp"

#include <glad/glad.h>

#include "engine/core/engine.hpp"


void OpenGL::InitFromGLAD() {
    this->Clear       = ::glClear;
    this->UseProgram  = ::glUseProgram;
    this->BindTexture = ::glBindTexture;
    this->Viewport    = ::glViewport;
    this->GetString   = ::glGetString;
    this->ClearColor = ::glClearColor;
    this->BlendFunc = ::glBlendFunc;
    this->PolygonMode = ::glPolygonMode;
    this->GenerateMipmap = ::glGenerateMipmap;
    this->CreateShader = ::glCreateShader;
    this->ShaderSource = ::glShaderSource;
    this->CompileShader = ::glCompileShader;
    this->CreateProgram = ::glCreateProgram;
    this->AttachShader = ::glAttachShader;
    this->LinkProgram = ::glLinkProgram;
    this->DeleteShader = ::glDeleteShader;
    this->GetProgramInfoLog = ::glGetProgramInfoLog;
    this->GetProgramiv = ::glGetProgramiv;
    this->GetActiveUniform = ::glGetActiveUniform;
    this->DeleteProgram = ::glDeleteProgram;
    this->GetShaderiv = ::glGetShaderiv;
    this->GetShaderInfoLog = ::glGetShaderInfoLog;
    this->PixelStorei = ::glPixelStorei;
    this->DrawArrays = ::glDrawArrays;
    this->DrawElements = ::glDrawElements;
    this->Uniform1i = ::glUniform1i;
    this->Uniform1f = ::glUniform1f;
    this->Uniform2fv = ::glUniform2fv;
    this->Uniform2f = ::glUniform2f;
    this->Uniform3fv = ::glUniform3fv;
    this->Uniform3f = ::glUniform3f;
    this->Uniform4fv = ::glUniform4fv;
    this->Uniform4f = ::glUniform4f;
    this->UniformMatrix2fv = ::glUniformMatrix2fv;
    this->UniformMatrix3fv = ::glUniformMatrix3fv;
    this->UniformMatrix4fv = ::glUniformMatrix4fv;
    this->GetUniformLocation = ::glGetUniformLocation;
    this->GenVertexArrays = ::glGenVertexArrays;
    this->BindVertexArray = ::glBindVertexArray;
    this->GenBuffers = ::glGenBuffers;
    this->BindBuffer = ::glBindBuffer;
    this->BufferData = ::glBufferData;
    this->BufferSubData = ::glBufferSubData;
    this->BindBufferBase = ::glBindBufferBase;
    this->EnableVertexAttribArray = ::glEnableVertexAttribArray;
    this->VertexAttribPointer = ::glVertexAttribPointer;
    this->DeleteVertexArrays = ::glDeleteVertexArrays;
    this->DeleteBuffers = ::glDeleteBuffers;
    this->GenTextures = ::glGenTextures;
    this->ActiveTexture = ::glActiveTexture;
    this->TexStorage3D = ::glTexStorage3D;
    this->TexParameteri = ::glTexParameteri;
    this->TexImage2D = ::glTexImage2D;
    this->GenFramebuffers = ::glGenFramebuffers;
    this->BindFramebuffer = ::glBindFramebuffer;
    this->FramebufferTexture2D = ::glFramebufferTexture2D;
    this->FramebufferTextureLayer = ::glFramebufferTextureLayer;
    this->DrawBuffer = ::glDrawBuffer;
    this->ReadBuffer = ::glReadBuffer;
    this->IsFramebuffer = ::glIsFramebuffer;
    this->IsTexture = ::glIsTexture;
    this->DeleteFramebuffers = ::glDeleteFramebuffers;
    this->DeleteTextures = ::glDeleteTextures;
    this->BlitFramebuffer = ::glBlitFramebuffer;
    this->Enable = ::glEnable;
    this->Disable = ::glDisable;
    this->CullFace = ::glCullFace;
    this->FrontFace = ::glFrontFace;
    this->TexImage2DMultisample = ::glTexImage2DMultisample;
    this->GenRenderbuffers = ::glGenRenderbuffers;
    this->BindRenderbuffer = ::glBindRenderbuffer;
    this->RenderbufferStorageMultisample = ::glRenderbufferStorageMultisample;
    this->RenderbufferStorage = ::glRenderbufferStorage;
    this->FramebufferRenderbuffer = ::glFramebufferRenderbuffer;
    this->CheckFramebufferStatus = ::glCheckFramebufferStatus;
    this->DeleteRenderbuffers = ::glDeleteRenderbuffers;
    this->DrawBuffers = ::glDrawBuffers;
    this->GetFramebufferAttachmentParameteriv = ::glGetFramebufferAttachmentParameteriv;
    this->GetError = ::glGetError;
    this->GetIntegerv = ::glGetIntegerv;
    this->DepthMask = ::glDepthMask;
    this->DepthFunc = ::glDepthFunc;
}